### PR TITLE
Update to 2.2.0

### PR DESCRIPTION
**Pull request by nedrichards**
this is likely going to need a tweak for appdata

### CODE REVIEW

**Comment by nedrichards** [comment]
I've filed a PR upstream with the diff that fixes the validator https://phabricator.kde.org/D28772

**Comment by jurf** [comment]
Have you started stitching out of quarantine boredom, Nick? :grinning:

**Comment by nedrichards** [comment]
Sadly not, my wife and daughter stitch though, so this is something I look out for.

**Comment by jurf** [comment]
It was similar here, the only problem was that this package never got used, so now I’m stuck with it. :P

**Comment by nedrichards** [comment]
Yeah, good point on that.

**Pull request merged**
